### PR TITLE
Add guiadence for fedora user to compile glava

### PR DESCRIPTION
**Pull request by ypraw**
hello, i'm fedora user and I have installed Glava on my system with some configurations that I have written in the readme. 

## Spefications
| Info | Value |
| :--- | :---- |
| OS  | Fedora 29 |
| Desktop Environtment | KDE Plasma |
| Kernel | 4.19.15-300.fc29.x86_64 |

## Screenshoot
image

### CODE REVIEW

**Comment by coderobe** [comment]
that's missing at least gcc and make, and libX11-devel looks unnecessary.

**Comment by wacossusca34** [comment]
> and libX11-devel looks unnecessary.

This package contains Xlib headers, so it would be necessary.

**Comment by ypraw** [comment]
hi, @coderobe ,

Thanks for your advice, i have added gcc and cmake with group c development and library tools package

**Comment by ypraw** [comment]
> This package contains Xlib headers, so it would be necessary.
hi @wacossusca34 , I think so too, I forgot what error I got before installing it, but it was useful for the build process

**Comment by ypraw** [comment]
@coderobe i don't know about ```how to best practice``` but imho this method is easier than having to install one by one.

**Comment by wacossusca34** [comment]
I'm going to close this simply because I have not had one user from a non debian-based distro have an issue with installing GLava's dependencies. This PR itself is a demonstration of that.

Anyone who wishes for an easier installation can also seek out a built GLava package for their distribution.

**Pull request closed without merging**
