### PR TITLE
Deleted trailing whitespaces.

### PR DESCRIPTION
**Pull request by thecsw**
Hey! I love glava!

I made a little PR to get rid of the trailing whitespaces. Nothing too serious, just trying to follow the coding style!

Thanks!

### CODE REVIEW

**Comment by coderobe** [comment]
Which coding style exactly? Looks like the whitespace is pretty consistent.

**Comment by thecsw** [comment]
1. Nondescript padding? 

2. The linux kernel coding style. Whitespaces are just taking up space in the source code. 

Some big reasons from [here](https://softwareengineering.stackexchange.com/questions/121555/why-is-trailing-whitespace-a-big-deal):
- It takes more storage space than necessary
- The parser will have to skip an extra character for no good reason when compiling
- Some editors might add an extra blank line when WordWrap is on and the trailing space doesn't fit

Note about whitespaces from Linus Torvalds in [linux coding style](https://www.kernel.org/doc/html/v4.10/process/coding-style.html):
> Do not leave trailing whitespace at the ends of lines. Some editors with smart indentation will insert whitespace at the beginning of new lines as appropriate, so you can start typing the next line of code right away. However, some such editors do not remove the whitespace if you end up not putting a line of code there, such as if you leave a blank line. As a result, you end up with lines containing trailing whitespace.

>Get a decent editor and don’t leave whitespace at the end of lines.

**Comment by coderobe** [comment]
1. Nondescript padding?
Yes, namely `Made a quick edit to [...]`, which amounts to 5 out of 11 words and doesn't describe what the commit does - if i were to accept this change, i'd squash it and rewrite the entire message. A bit hypocritical given your change, don't you think?

    Some big reasons
Your reasons are anything but "big", anyways - i'm gonna leave it up to @wacossusca34 to merge this..

**Comment by thecsw** [comment]
Yeah, my bad about giving this commit a bad message. I will rename the PR and if it gets merged, squash merge will save me.

Just wanted to add some other sources about white spaces. It was a pleasure

**Comment by wacossusca34** [comment]
The provided reasons here are pedantic at best:

> It takes more storage space than necessary

If we are worried about what would amount to <1Kb of storage then the system in question probably can't run GLava at all.

> The parser will have to skip an extra character for no good reason when compiling

Tokenizing source files is a very small fraction of the compile time, and whitespace almost certainly amounts to time that could be measured in a few dozen cycles. If you want to micro-optimize like this, then perhaps it's better to peer at GLava's shaders.

> Some editors might add an extra blank line when WordWrap is on and the trailing space doesn't fit

This can easily be solved by using Emacs.

Also, in `CONTRIBUTING.md`:

> Anything not mentioned here is **probably subjective** and won't hurt your chances of getting a PR accepted.

I honestly am not that strict about code style, I just made that document so people have an idea of what kind of formatting is preferred. As @coderobe mentioned:

> Looks like the whitespace is pretty consistent throughout the files

And he is correct. This is a habit and setting I have in my editor, pressing `TAB` automatically aligns the current line to the indentation level with extra spacing, regardless of whether the line has contents or not.

I don't mind code style PRs, but they should actually contribute to readability.

**Pull request closed without merging**
