### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by Aaahh**
Won't build without this change, guessing glx renamed to gl

### CODE REVIEW

**Comment by wacossusca34** [comment]
On my system:

```bash
~/C/GLava$ ls /usr/lib | grep GLX
libGLX_indirect.so.0
libGLX_mesa.so
libGLX_mesa.so.0
libGLX_mesa.so.0.0.0
libGLX_nvidia.so
libGLX_nvidia.so.0
libGLX_nvidia.so.387.34
libGLX.so
libGLX.so.0
libGLX.so.0.0.0
```

I'm not sure why `libGLX` does not exist on your system. Perhaps this is something I can solve with `glad` instead, since it provides an option for generating GLX bindings and extensions as well.

**Comment by Aaahh** [comment]
I have nvidia prime and intel Mesa
Installing libglx1 basically uninstalsls everything

**Comment by wacossusca34** [comment]
What distro and/or package manager are you using?

**Comment by Aaahh** [comment]
Running Ubuntu 18.04 Unity Remix Edition (basically stock Ubuntu 18.04), apt-get
Intel  7th integrated and Nvidia
I was missing libglx0, but even after install gcc can't find it

aaahh@aaahh:/usr/lib$ ls -R | grep GLX
libGLX_indirect.so.0
libGLX_nvidia.so.0
libGLX_nvidia.so.384.111
libGLX.so
libGLX.so.0
libGLX.so.0
libGLX.so.0.0.0

**Comment by wacossusca34** [comment]
> I was missing libglx0, but even after install gcc can't find it

if GCC can't find `libGLX.so` despite it actually existing in `/usr/lib`, there's something else going on here that is outside the scope of GLava's makefile.

**Comment by Aaahh** [comment]
sudo ln -s /usr/lib/nvidia-384/libGLX.so /usr/lib 
I should have noticed that from the beginning, sorry lad

**Comment by Aaahh** [comment]
Using the libGLX.so from nvidia-384 
`aaahh@aaahh:~/glava$ glava
Using backend: 'glx'
glXChooseFBConfig(): failed
Aborted (core dumped)`

Switching back to libGL.so works great

**Comment by wacossusca34** [comment]
I think this is some complexity involving selecting the right GLX implementation on PRIME and Bumblebee systems. I will just get glad to handle GLX bindings, then, since I'm pretty sure it handles this case properly.

**Pull request closed without merging**
